export const projects = [
  {
    id: 1,
    image: "src/assets/cars.jpg",
    category: "Business",
    name: "Opening a Car Dealership",
    description: "A project to open a modern premium-class car dealership",
    raised: "$11.87",
    goal: "$500,000",
    daysLeft: 30,
    author: "AutoKing99",
    status: "active"
  },
  {
    id: 2,
    image: "src/assets/nature.jpg",
    category: "Ecology",
    name: "Save Nature",
    description: "A project to protect the environment and endangered species",
    raised: "$3.60",
    goal: "$8,000",
    daysLeft: 45,
    author: "EcoWarrior7",
    status: "active"
  },
  {
    id: 3,
    image: "src/assets/tech.jpg",
    category: "Technology",
    name: "Smart Home",
    description: "Development of a smart home system based on AI",
    raised: "$500",
    goal: "$2,000",
    daysLeft: 60,
    author: "TechGuru81",
    status: "active"
  },
  {
    id: 4,
    image: "src/assets/art.jpg",
    category: "Art",
    name: "Mosaic of the Future",
    description: "Creating a large-scale art installation for public spaces",
    raised: "$2,000",
    goal: "$10,000",
    daysLeft: 30,
    author: "ArtVisionary",
    status: "active"
  },
  {
    id: 5,
    image: "src/assets/comics.jpg",
    category: "Comics",
    name: "Heroes from the Dark Streets",
    description: "A comic about heroes fighting crime in a metropolis",
    raised: "$500",
    goal: "$2,500",
    daysLeft: 15,
    author: "ComicMaster22",
    status: "active"
  },
  {
    id: 6,
    image: "src/assets/crafts.jpg",
    category: "Crafts",
    name: "Handmade: From Dream to Reality",
    description: "A project dedicated to creating unique handmade items",
    raised: "$150",
    goal: "$2,000",
    daysLeft: 20,
    author: "CraftQueen01",
    status: "active"
  },
  {
    id: 7,
    image: "src/assets/dance.jpg",
    category: "Dance",
    name: "Dance Across Continents",
    description: "An international project to popularize dance cultures",
    raised: "$1,200",
    goal: "$10,000",
    daysLeft: 25,
    author: "DancerInMotion",
    status: "active"
  },
  {
    id: 8,
    image: "src/assets/design.jpg",
    category: "Design",
    name: "Design of the New Generation",
    description: "Creating innovative design concepts for modern offices",
    raised: "$8,000",
    goal: "$20,000",
    daysLeft: 18,
    author: "DesignPro99",
    status: "active"
  },
  {
    id: 9,
    image: "src/assets/fashion.jpg",
    category: "Fashion",
    name: "Fashion Without Borders",
    description: "A collection of clothing that blends different cultures",
    raised: "$5,000",
    goal: "$15,000",
    daysLeft: 10,
    author: "FashionIcon07",
    status: "active"
  },
  {
    id: 10,
    image: "src/assets/film.jpg",
    category: "Film",
    name: "Light at the End of the Tunnel",
    description: "A documentary film about people overcoming difficult life challenges",
    raised: "$2,000",
    goal: "$5,000",
    daysLeft: 14,
    author: "FilmMaker33",
    status: "active"
  },
  {
    id: 11,
    image: "src/assets/food.jpg",
    category: "Food",
    name: "Delicious Journeys",
    description: "A project dedicated to creating a culinary show about different countries",
    raised: "$3,000",
    goal: "$10,000",
    daysLeft: 30,
    author: "ChefExtraordinaire",
    status: "active"
  },
  {
    id: 12,
    image: "src/assets/games.jpg",
    category: "Games",
    name: "Fantasy Game World",
    description: "Creating a game where players can create their own worlds",
    raised: "$50,000",
    goal: "$150,000",
    daysLeft: 30,
    author: "GameMaster123",
    status: "active"
  },
  {
    id: 13,
    image: "src/assets/journalism.jpg",
    category: "Journalism",
    name: "A New Perspective on Events",
    description: "A project to create a new online publication with a unique approach to news",
    raised: "$1,500",
    goal: "$5,000",
    daysLeft: 12,
    author: "JournoExpert",
    status: "active"
  },
  {
    id: 14,
    image: "src/assets/music.jpg",
    category: "Music",
    name: "Sound of the Future",
    description: "An album combining various music genres from classical to electronic",
    raised: "$3,000",
    goal: "$8,000",
    daysLeft: 28,
    author: "SoundMaster87",
    status: "active"
  },
  {
    id: 15,
    image: "src/assets/photography.jpg",
    category: "Photography",
    name: "Moments of Life",
    description: "A photography project dedicated to capturing the lives of ordinary people",
    raised: "$2,500",
    goal: "$10,000",
    daysLeft: 6,
    author: "ShutterBug04",
    status: "active"
  },
  {
    id: 16,
    image: "src/assets/publishing.jpg",
    category: "Publishing",
    name: "Talents of Youth",
    description: "A book that collects the best works of young writers",
    raised: "$1,200",
    goal: "$5,000",
    daysLeft: 16,
    author: "WriterXpress",
    status: "active"
  },
  {
    id: 17,
    image: "src/assets/technology.jpg",
    category: "Technology",
    name: "Future in Your Hands",
    description: "A project to develop a device to improve the quality of life for people with disabilities",
    raised: "$1,000",
    goal: "$3,000",
    daysLeft: 20,
    author: "TechRevolutioner",
    status: "active"
  },
  {
    id: 18,
    image: "src/assets/art.jpg",
    category: "Art",
    name: "Street Style Painting",
    description: "A project to create street art murals in public spaces in the city",
    raised: "$800",
    goal: "$4,000",
    daysLeft: 10,
    author: "UrbanArtist91",
    status: "active"
  },
  {
    id: 19,
    image: "src/assets/comics.jpg",
    category: "Comics",
    name: "Adventures in an Alternate Universe",
    description: "Creating comics about adventures through alternate universes",
    raised: "$700",
    goal: "$3,500",
    daysLeft: 8,
    author: "ComicRider",
    status: "active"
  },
  {
    id: 20,
    image: "src/assets/crafts.jpg",
    category: "Crafts",
    name: "Miniature Masterpieces",
    description: "A project to create miniature figurines and models",
    raised: "$1,000",
    goal: "$5,000",
    daysLeft: 18,
    cauthor: "MiniMaster",
    status: "active"
  },
  {
    id: 21,
    image: "src/assets/dance.jpg",
    category: "Dance",
    name: "Dancing on Water",
    description: "A project to create a unique dance program performed on water",
    raised: "$4,500",
    goal: "$12,000",
    daysLeft: 23,
    author: "WaterDancer77",
    status: "active"
  },
  {
    id: 22,
    image: "src/assets/design.jpg",
    category: "Design",
    name: "Modern Interiors",
    description: "A project to develop modern designs for residential and office spaces",
    raised: "$3,000",
    goal: "$7,000",
    daysLeft: 26,
    author: "InteriorPro",
    status: "active"
  },
  {
    id: 23,
    image: "src/assets/fashion.jpg",
    category: "Fashion",
    name: "Clothes for the Future",
    description: "A clothing collection using advanced technologies and fabrics",
    raised: "$9,000",
    goal: "$25,000",
    daysLeft: 15,
    author: "FutureFitDesign",
    status: "active"
  },
  {
    id: 24,
    image: "src/assets/film.jpg",
    category: "Film",
    name: "Dreams of Cinema",
    description: "A project to create an independent film with an unconventional concept",
    raised: "$2,500",
    goal: "$6,000",
    daysLeft: 9,
    author: "IndieFilmmaker",
    status: "active"
  },
  {
    id: 25,
    image: "src/assets/food.jpg",
    category: "Food",
    NavigationPreloadManager: "Sweet Fantasies",
    description: "A project to create a patisserie offering unique desserts",
    raised: "$600",
    goal: "$4,000",
    daysLeft: 12,
    author: "SugarCraft",
    status: "active"
  },
  {
    id: 26,
    image: "src/assets/games.jpg",
    category: "Games",
    name: "Games for All",
    description: "A project to create accessible games for people with disabilities",
    raised: "$2,000",
    goal: "$8,000",
    daysLeft: 25,
    author: "GameDevX",
    status: "active"
  },
  {
    id: 27,
    image: "src/assets/journalism.jpg",
    category: "Journalism",
    name: "The Voice of Freedom",
    description: "A project dedicated to creating an online news platform for independent journalism",
    raised: "$3,500",
    goal: "$10,000",
    daysLeft: 20,
    author: "PressForce",
    status: "active"
  },
  {
    id: 28,
    image: "src/assets/music.jpg",
    category: "Music",
    name: "Music for the Soul",
    description: "An album combining music from different cultures and genres",
    raised: "$4,000",
    goal: "$12,000",
    daysLeft: 5,
    author: "SoulVibes",
    status: "active"
  },
  {
    id: 29,
    image: "src/assets/photography.jpg",
    category: "Photography",
    name: "Capturing the Moment",
    description: "A project to create a photo book capturing emotional moments of people’s lives",
    raised: "$2,000",
    goal: "$7,000",
    daysLeft: 30,
    author: "LensMaster",
    status: "active"
  },
  {
    id: 30,
    image: "src/assets/publishing.jpg",
    category: "Publishing",
    name: "Timeless Stories",
    description: "A project to publish a series of short stories from young authors",
    raised: "$1,500",
    goal: "$5,000",
    daysLeft: 16,
    author: "StoryTellerX",
    status: "active"
  }
];
